[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/dist/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/dist/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/dist/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  fail_deploy_on_score_thresholds = false  # Ubah ke true jika ingin gagal deploy saat skor rendah